#' Run prevalence changes analysis for a cohort and save results to PostgreSQL
#'
#' @description This function runs the prevalence changes analysis for a given
#' cohort and saves the results to PostgreSQL database. This function is designed
#' to be called during cohort evaluation to populate the database with prevalence
#' changes analysis results.
#'
#' @param cohort_id cohort identifier to analyze
#' @param scratch.table space and table where the cohort is available
#' @param cdm_schema general database cdm schema
#' @param concept_sets data frame containing concept sets information
#' @param conn database connection for querying data
#' @param postgres_conn PostgreSQL connection for saving results
#' @param database_id database identifier for the analysis
#' @param server server name for logging
#' @param drivers_dir directory containing database drivers
#' @param progress progress object for UI updates (optional)
#' @param schema_name PostgreSQL schema name (default: "phenotype_library")
#'
#' @return data.table with prevalence changes analysis results
#'
#' @details
#'
#' ## Required packages
#' * data.table
#' * DBI
#' * PLNewFeatures
#'
#' ## Functions Called
#' - prevalence_changes: Main prevalence changes analysis function
#'
#' ## PostgreSQL Tables Created/Updated
#' - prevalence_changes: Prevalence changes analysis results
#'
#' @examples
#' \dontrun{
#' # Run prevalence changes analysis for a cohort
#' results <- prevalence_changes_analysis(
#'   cohort_id = 123,
#'   scratch.table = "scratch.cohort_table",
#'   cdm_schema = "cdm_schema",
#'   concept_sets = concept_sets_df,
#'   conn = redshift_conn,
#'   postgres_conn = postgres_conn,
#'   database_id = "optum_ehr",
#'   server = "server_name",
#'   drivers_dir = "drivers",
#'   progress = progress_obj
#' )
#' }
#'
#' @author Luisa Martínez (08APR2025)
#' @export
#' @family prevalence_changes_analysis
prevalence_changes_analysis <- function(cohort_id,
                                       scratch.table,
                                       cdm_schema,
                                       concept_sets,
                                       conn,
                                       postgres_conn,
                                       database_id,
                                       server,
                                       drivers_dir,
                                       progress = NULL,
                                       schema_name = "phenotype_library") {
  
  checkmate::assert_numeric(cohort_id)
  checkmate::assert_string(scratch.table, min.chars = 1)
  checkmate::assert_string(cdm_schema, min.chars = 1)
  checkmate::assert_data_frame(concept_sets)
  checkmate::assert_class(conn, "DatabaseConnectorJdbcConnection")
  checkmate::assert_class(postgres_conn, "DatabaseConnectorJdbcConnection")
  checkmate::assert_string(database_id, min.chars = 1)
  checkmate::assert_string(server, min.chars = 1, na.ok = TRUE)
  checkmate::assert_directory_exists(drivers_dir)
  
  logger::log_info("Starting prevalence changes analysis for cohort_id: ", cohort_id, 
                  " and database_id: ", database_id)
  
  # Run prevalence changes analysis
  logger::log_info("Running prevalence_changes analysis...")
  tryCatch({
    results <- prevalence_changes(
      cohort_id = cohort_id,
      scratch = scratch.table,
      cdm_schema = cdm_schema,
      concept_sets = concept_sets,
      conn = conn,
      postgres_conn = postgres_conn,
      postgres_table_name = "prevalence_changes",
      database_id = database_id,
      schema_name = schema_name
    )
    
    logger::log_success("Prevalence changes analysis completed successfully for cohort_id: ", 
                       cohort_id, " and database_id: ", database_id)
    
    return(results)
    
  }, error = function(e) {
    logger::log_error("Error in prevalence changes analysis for cohort_id ", cohort_id, 
                     " and database_id ", database_id, ": ", e$message)
    stop("Prevalence changes analysis failed: ", e$message)
  })
}

#' Get prevalence changes analysis output table names
#'
#' @description Returns the list of table names that are generated by the
#' prevalence changes analysis functions.
#'
#' @return character vector of table names
#'
#' @author Luisa Martínez (08APR2025)
#' @export
#' @family prevalence_changes_analysis
get_prevalence_changes_analysis_output_table_names <- function() {
  tables <- c(
    "prevalence_changes"
  )
  
  return(tables)
}
